version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/maven1"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.ow2.asm:*"
  - package-ecosystem: "maven"
    directory: "/maven2"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.jetbrains.kotlin:*"
